### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Al3601** [nmarsh92/tribemanagerapi#2]
Hi, 

Can you please explain how i can get this work ?  where to add my discord oauth2 and how i can set it with your tribemanager web app.

Thank you

**Comment by nmarsh92** [comment]
Sure, sorry I didn't get far enough to make it super easily extensible. I
pushed my latest code just now, not sure what changes were made from the
diff it's been a few months.

I use digital ocean to serve both the front end and the api.
 Here is a link on how to configure Nginx to reverse proxy with node so
that you can use SSL for the api requests.
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

I added tables.sql to the api which is the create statement for all the
tables I use.
speciesdata.sql has the data dump for all of the breedable species and a
few other commonly used ones like griffins in ark at the time of writing(no
abberration)

You will need to manually add an entry into "Tribes" table with a guid Id
and a friendly name for the tribe. This will let first time users select
what tribe they are in if you have multiple tribes in the alliance, which
is used to separate out the data. If you only have one tribe, just add one
entry it is required for the web app though.


You need to setup a discord bot and add the callback url e.g. (
https://sample.com:3002/discord/callback)

Update the sample config.json file with your configurations and rename it
to "config.json" I just updated it to reflect my production version.

I just added sample_config.js and pushed my latest code
Modify sample_config.js with your api url and the tribe_ids in the
generators array is from the Tribes table you manually inserted into, it
allows people in that tribe to see the generators tab.
Rename sample_config.js to config.js

Use the node/gulpfile to bundle the project and host it in your web server

If you have any other questions feel free to ask.


Nathan Marsh

**Comment by Al3601** [comment]
thank for quick reply !

actually im stuck with starting the tribemanagerapi, what di you mean by "Use the node/gulpfile to bundle the project" ?

in my config.json i set the api url like this 

`  "tribeManagerApp": {
    "url": "http://localhost:3002"
`

same on the config.js 

`api:{
    baseUrl: "http://localhost:3002"
  }`

when i start the tribemanagerapi " node index.js start" it just print 

> ... port 8080 in development mode
Database connected...

> 

when i go to http://EXTERNAL_IP:3002  or http://EXTERNAL_IP:8080 or http://EXTERNAL_IP:8081, there is nothing and no BOT conneting to my discord.

**Comment by nmarsh92** [comment]
The url in config.json should point to the web app not the service. It's
used in controllers/discord controller exports.callback to let the API know
where to go after the discord bot returns.

When i go to the url for the base of the API I get "cannot GET /", it's not
setup to be a ping page or anything. So you could call some of the routes
in routes/arkRoutes.js but they'll probably all return 401 without the
authorization being sent correctly.

The API works in congruence with the web app

https://github.com/nmarsh92/tribemanager

Which is the project with the gulp task I was referring to. So you would go
to the virtual path for where it was hosted to get it to call the discord
bot. If you don't want to do the bundeling then you would need to add all
of the paths to the script files in the index.html file since it only
references the bundle file dist/1.1/scripts/tribe-manager.angular1.min.js


On Dec 18, 2017 5:07 AM, "Al3601" <notifications@github.com> wrote:

thank for quick reply !

actually im stuck with starting the tribemanagerapi, what di you mean by
"Use the node/gulpfile to bundle the project" ?

in my config.json i set the api url like this

"tribeManagerApp": { "url": "http://localhost:3002"

same on the config.js

api:{ baseUrl: "http://localhost:3002" }

when i start the tribemanagerapi " node index.js start" it just print

... port 8080 in development mode
Database connected...

when i go to http://EXTERNAL_IP:3002 or http://EXTERNAL_IP:8080 or
http://EXTERNAL_IP:8081, there is nothing and no BOT conneting to my
discord.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nmarsh92/tribemanagerapi/issues/2#issuecomment-352381350>,
or mute the thread

**Comment by nmarsh92** [comment]
No reply in a long time. Marking as resolved.
